openapi: 3.0.0
info:
  title: Land Management API
  version: 1.0.0
  description: Basic API description

paths:
  /test:
    get:
      tags:
        - test
      summary: say hello
      description: say hello
      operationId: sayHello
      responses:
        '200':
          description: Successful hello response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello World
        '500':
          description: Internal server error